version: "3"

# Load environment variables from .env file if it exists
dotenv:
  - .env
  - .env.example?

tasks:
  setup:
    desc: Initial setup for development
    cmds:
      - chmod +x ./setup.sh
      - ./setup.sh

  start:
    desc: Start all containers
    cmds:
      - docker-compose up -d
      - sleep 3
      - docker-compose ps

  start-db:
    desc: Start only the Postgres container
    cmds:
      - docker-compose up -d postgres
      - sleep 3
      - docker-compose ps postgres

  start-backend:
    desc: Start the backend service
    deps: [start-db]
    cmds:
      - docker-compose up -d backend
      - docker-compose ps backend

  start-frontend:
    desc: Start the frontend service
    deps: [start-backend]
    cmds:
      - docker-compose up -d frontend
      - docker-compose ps frontend

  stop:
    desc: Stop all containers
    cmds:
      - docker-compose down

  sqlc:
    desc: Generate Go code from SQL using sqlc
    dir: backend
    cmds:
      - sqlc generate

  reset-db:
    desc: Reset the database (destroy and recreate)
    cmds:
      - docker-compose down -v postgres
      - docker-compose up -d postgres

  psql:
    desc: Connect to Postgres with psql
    cmds:
      - docker-compose exec postgres psql -U {{.POSTGRES_USER | default "appuser"}} -d {{.POSTGRES_DB | default "appdb"}}

  logs:
    desc: View logs from all services
    cmds:
      - docker-compose logs -f

  logs-backend:
    desc: View backend logs
    cmds:
      - docker-compose logs -f backend

  logs-frontend:
    desc: View frontend logs
    cmds:
      - docker-compose logs -f frontend

  build:
    desc: Build all containers without starting them
    cmds:
      - docker-compose build
