# Install air : go install github.com/air-verse/air@latest

# Root directory of the project
root = "."

# Command to run the server
cmd = "./tmp/server"

# Watching for file changes
[watcher]
include = ["**/*.go"]
exclude = ["./tmp/*", "_test.go", "vendor/*"]

# Build settings
[build]
bin = "./tmp/server"                       # Binary file
cmd = "go build -o ./tmp/server server.go"
delay = 1000                               # Delay in milliseconds before restarting
kill_signal = "SIGTERM"

# Logging settings
[log]
level = "debug"

# Misc settings
[color]
error = "red"
warning = "yellow"
info = "blue"

# [screen]
# clear_on_rebuild = false
