name: Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: work-flow-tests
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod download

      - name: Verify server.go exists
        run: |
          ls -la
          if [ -f server.go ]; then echo "server.go exists"; else echo "server.go does not exist!" && exit 1; fi

      - name: Build server
        run: go build -v ./...

      - name: Fetch main branch
        run: git fetch origin main

      - name: Test backend
        env:
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SMTP_ENDPOINT_ADDRESS: ${{ vars.SMTP_ENDPOINT_ADDRESS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_TLS_MODE: ${{ vars.SMTP_TLS_MODE }}
          SMTP_TEST_EMAIL: ${{vars.SMTP_TEST_EMAIL}}
          SMTP_FROM: ${{vars.SMTP_FROM}}
        run: |
          go test ./...