name: Integration Tests

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/integration.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate docker-compose
        run: docker-compose config
      
      - name: Start database
        run: docker-compose up -d postgres
      
      - name: Wait for database to be ready
        run: |
          timeout=60
          while ! docker-compose exec -T postgres pg_isready -U appuser 2>/dev/null; do
            timeout=$((timeout-1))
            if [ $timeout -eq 0 ]; then
              echo "Timeout waiting for database to be ready"
              exit 1
            fi
            echo "Waiting for database to be ready..."
            sleep 1
          done
          echo "Database is ready!"
      
      - name: Verify database connection
        run: |
          docker-compose exec -T postgres psql -U appuser -d appdb -c "SELECT 1;"